namespace NepFix
{
    /// Переводы интерфейса: русский оригинал, английский перевод.
    internal static class LocData
    {
        public static readonly string[] Pairs =
        {
            @"≡ NepFix {0} — графика и исправления   [{1} — закрыть, тянуть за заголовок]", @"≡ NepFix {0} — graphics and fixes   [{1} to close, drag by the title]",
            @"Экран", @"Display",
            @"Качество", @"Quality",
            @"Сглаживание", @"Anti-aliasing",
            @"Тени", @"Shadows",
            @"Дальность", @"Distance",
            @"Персонажи", @"Characters",
            @"Исправления", @"Fixes",
            @"Мониторинг", @"Monitoring",
            @"Моды", @"Mods",
            @"Оверлей", @"Overlay",
            @"Оптимизация", @"Performance",
            @"Освещение", @"Lighting",
            @"Диагностика в лог", @"Diagnostics to log",
            @"Записано в LogOutput.log", @"Written to LogOutput.log",
            @"Сбросить вкладку", @"Reset tab",
            @"Вкладка сброшена", @"Tab reset",
            @"Сбросить всё", @"Reset all",
            @"Все настройки сброшены", @"All settings reset",
            @"Управлять FPS, снять лимит 60", @"Control FPS, remove 60 cap",
            @"Лимит FPS", @"FPS limit",
            @"Лимит FPS в бою", @"FPS limit in battle",
            @"Спутники обходят препятствия", @"Party members path around obstacles",
            @"Спутники догоняют без вспышки", @"Party members catch up without the flash",
            @"Спутники на карте обходят препятствия по маршруту, а не упираются в них.", @"Party members on the map follow a route around obstacles instead of running into them.",
            @"Отставший спутник переносится без вспышки за кадр, под камеру, и догоняет отряд сам.", @"A party member that falls behind is moved off-screen, under the camera, without the flash, and catches up on its own.",
            @"Если в бою боссы атакуют слишком часто и бьют слишком больно, поставьте здесь 60: игра рассчитана на 60 кадров. Переключать можно прямо во время боя.", @"If bosses attack too often and hit too hard in battle, set this to 60: the game is designed for 60 FPS. You can switch it during a battle.",
            @"без ограничения", @"unlimited",
            @"60, как задумано игрой", @"60, as the game intends",
            @"Лимит FPS в бою. Игра рассчитывает бой на 60 кадров: если боссы атакуют слишком часто и бьют слишком больно, поставьте 60. 0 = без ограничения.", @"FPS limit in battle. The game is designed for 60 FPS in battle: if bosses attack too often and hit too hard, set 60. 0 = unlimited.",
            @"как монитор, {0}", @"monitor, {0}",
            @"Вертикальная синхронизация", @"Vertical sync",
            @"Кадров в очереди GPU", @"GPU queued frames",
            @"как в игре", @"game default",
            @"1, минимальная задержка", @"1, lowest latency",
            @"Оверлей мониторинга", @"Performance overlay",
            @"выкл", @"off",
            @"компактный", @"compact",
            @"подробный", @"detailed",
            @"подробный + график", @"detailed + graph",
            @"Рендер: ", @"Renderer: ",
            @"Текущая цель: {0} FPS. Скорость игры привязана к целевому FPS: ставьте значение, которое ПК стабильно держит.", @"Current target: {0} FPS. Game speed is tied to the target FPS, so pick a value your PC can hold steadily.",
            @"Профиль Unity", @"Unity quality profile",
            @"Текстуры в полном разрешении", @"Full-resolution textures",
            @"Анизотропная фильтрация", @"Anisotropic filtering",
            @"Скиннинг по 4 костям, плавнее суставы", @"4-bone skinning, smoother joints",
            @"Резкость текстур", @"Texture sharpness",
            @"HDR-рендеринг", @"HDR rendering",
            @"Профиль Normal, который стоит в игре по умолчанию, грузит текстуры в половинном разрешении и считает скиннинг по 2 костям.", @"The game's default Normal profile loads textures at half resolution and skins with only 2 bones.",
            @"ReShade активен, поэтому MSAA выключен: ReShade нужен буфер глубины. Используйте SMAA и масштаб рендера.", @"ReShade is active, so MSAA is off: ReShade needs the depth buffer. Use SMAA and render scale instead.",
            @"Пост-сглаживание", @"Post-process AA",
            @"SMAA низк.", @"SMAA low",
            @"SMAA сред.", @"SMAA medium",
            @"SMAA выс.", @"SMAA high",
            @"Режим FSR", @"FSR mode",
            @"Внутреннее разрешение {0}x{1}, {2}% от экрана, растягивает AMD FSR 1.0.", @"Internal resolution {0}x{1}, {2}% of the screen, upscaled by AMD FSR 1.0.",
            @"Масштаб рендера", @"Render scale",
            @"Апскейлер при масштабе меньше 1", @"Upscaler below scale 1",
            @"авто", @"auto",
            @"билинейный", @"bilinear",
            @"точечный", @"point",
            @"Резкость FSR", @"FSR sharpness",
            @"Против лесенок на персонажах: MSAA 4x, SMAA и масштаб 1.25–1.5. Режимы FSR уменьшают внутреннее разрешение ради FPS. Native AA рисует в полном разрешении и только повышает резкость.", @"Against jaggies on characters: MSAA 4x, SMAA and scale 1.25–1.5. FSR modes lower the internal resolution for FPS. Native AA renders at full resolution and only sharpens.",
            @"Управлять тенями", @"Control shadows",
            @"Разрешение теней", @"Shadow resolution",
            @"Мин. дальность теней", @"Min. shadow distance",
            @"{0} м", @"{0} m",
            @"Множитель дальности", @"Distance multiplier",
            @"Каскады", @"Cascades",
            @"Мягкие тени", @"Soft shadows",
            @"Тени от дополнительных источников света", @"Shadows from additional lights",
            @"SSAO, затенение в углах и под ногами", @"SSAO, shading in corners and under feet",
            @"Дальность растительности и мелких объектов", @"Grass and small object distance",
            @"без отсечения", @"no culling",
            @"Дальность отсечения камеры", @"Camera far clip distance",
            @"Отключить упрощение объектов карты", @"Disable map object simplification",
            @"Изменение дальности и упрощения карты применяется при следующей загрузке локации.", @"Distance and map simplification changes apply on the next area load.",
            @"Толщина контура", @"Outline width",
            @"авто, {0}x", @"auto, {0}x",
            @"Принудительно: тени от всех частей моделей", @"Force: shadows from all model parts",
            @"Удары вне боя", @"Field attacks",
            @"Плавное появление оружия", @"Smooth weapon appearance",
            @"Длительность появления", @"Appearance duration",
            @"{0} мс", @"{0} ms",
            @"Плавность переходов анимаций", @"Animation transition smoothness",
            @"как в игре, 100 мс", @"game default, 100 ms",
            @"Мотоцикл", @"Bike",
            @"Плавное движение отряда и мотоцикла", @"Smooth party and bike movement",
            @"Сейчас включён и «Шаг физики под FPS» на вкладке «Исправления». Лучше выключить его: вместе они не нужны и нагружают процессор.", @"""Physics step matched to FPS"" on the Fixes tab is also on. Better turn it off: you don't need both, and together they load the CPU.",
            @"Игра двигает героинь и мотоцикл только на шагах физики, из-за этого рывки. Сглаживается объектов: {0}.", @"The game moves the heroines and the bike only on physics steps, which causes stutter. Objects smoothed: {0}.",
            @"Управляемость", @"Handling",
            @"Максимальная скорость", @"Top speed",
            @"Мягкость ударов о стену", @"Wall hit softness",
            @"Плавный подъём на уступы", @"Smooth ledge climbing",
            @"Замер езды на мотоцикле", @"Bike ride recording",
            @"Включите, сядьте на мотоцикл и поездите минуту: повороты, ускорение, пару столкновений. Каждый замер пишется в отдельный файл BepInEx\NepFix_bike_дата_время.csv.", @"Turn it on, get on the bike and ride for a minute: turns, acceleration, a couple of crashes. Each recording goes to its own file, BepInEx\NepFix_bike_date_time.csv.",
            @"Голос", @"Voice",
            @"Пауза между фразами на карте", @"Pause between field voice lines",
            @"{0} с", @"{0} s",
            @" Разговоры в сценах и по кнопке взаимодействия не затрагиваются.", @" Cutscene dialogue and interaction lines are not affected.",
            @"Обработано материалов персонажей: {0}. Контур в игре рассчитан на 1080p, на 1440p он тоньше и рвётся; «авто» масштабирует по разрешению.", @"Character materials processed: {0}. The game's outline is designed for 1080p and gets thin and broken at 1440p; ""auto"" scales it with resolution.",
            @"Тайминг по реальному времени кадра", @"Frame-time based timing",
            @"Враги не застревают при высоком FPS", @"Enemies don't get stuck at high FPS",
            @"Юнит бросал путь, считая что упёрся: {0} раз. Мод вернул на путь: {1} раз.", @"Units gave up their path thinking they were blocked: {0} times. Put back on the path by the mod: {1} times.",
            @"Интерполяция физики против дёрганья", @"Physics interpolation against stutter",
            @"Шаг физики под FPS, эксперимент", @"Physics step matched to FPS, experimental",
            @"Не включайте вместе с «Плавным движением отряда и мотоцикла» на вкладке «Персонажи»: сглаживание уже убирает рывки, а частая физика только нагружает процессор и даёт фризы.", @"Don't combine with ""Smooth party and bike movement"" on the Characters tab: smoothing already removes stutter, and frequent physics only loads the CPU and causes freezes.",
            @"Аниматоры не засыпают вне кадра, эксперимент", @"Animators stay awake off-screen, experimental",
            @"Плавное движение персонажей", @"Smooth character movement",
            @"Сглаживание высоты", @"Height smoothing",
            @"Сглаживается персонажей: {0}. Игра прижимает персонажей к земле 50 раз в секунду, а кадров больше, поэтому без сглаживания модель подпрыгивает по высоте.", @"Characters smoothed: {0}. The game snaps characters to the ground 50 times per second, but there are more frames, so without smoothing the model bobs up and down.",
            @"Постановка ступней по земле", @"Foot placement on ground",
            @"Физика волос и одежды", @"Hair and cloth physics",
            @"частота под FPS", @"rate matched to FPS",
            @"раз в кадр", @"once per frame",
            @". Если волосы дрожат, попробуйте «раз в кадр».", @". If hair jitters, try ""once per frame"".",
            @"Компонентов постановки ступней в сцене: {0}. Если ноги дрожат при медленной ходьбе, выключите: ступни перестанут подстраиваться под неровности.", @"Foot placement components in scene: {0}. If legs jitter when walking slowly, turn it off: feet will stop adapting to uneven ground.",
            @"Подробный лог", @"Verbose log",
            @"Источник данных GPU: {0}. Обновление раз в 0,5 с в фоновом потоке.", @"GPU data source: {0}. Updated every 0.5 s in a background thread.",
            @"Проверка…", @"Checking…",
            @"Обновить список", @"Refresh list",
            @"HD-текстуры по данным из памяти игры: ", @"HD textures according to game memory: ",
            @"Сейчас FPS ограничивает: {0}. GPU {1}, FPS {2} из {3}.", @"FPS is currently limited by: {0}. GPU {1}, FPS {2} of {3}.",
            @"Готовые пресеты:", @"Presets:",
            @"Макс. качество", @"Max quality",
            @"Баланс, рекомендуется", @"Balanced, recommended",
            @"Макс. FPS", @"Max FPS",
            @"Не считать скиннинг вне кадра", @"Skip off-screen skinning",
            @"Физика без авто-синхронизации, могут дрожать ноги", @"Physics without auto-sync, legs may jitter",
            @"Ускоренная загрузка ресурсов", @"Faster asset loading",
            @"Аниматоры вне кадра не обновляются, эксперимент", @"Off-screen animators don't update, experimental",
            @"Резкость применена к {0} текстурам. Дороже всего для процессора каскады теней, каждый заново рисует сцену, тени от точечных источников, до 6 проходов на каждый, LOD Bias выше 2 и дальность теней больше 100 м.", @"Sharpness applied to {0} textures. The most CPU-expensive settings are shadow cascades (each redraws the scene), point light shadows (up to 6 passes each), LOD Bias above 2 and shadow distance over 100 m.",
            @"DXVK на видеокартах NVIDIA обычно медленнее родного DirectX 11 в играх, упирающихся в процессор: трансляция добавляет работу CPU. Для максимума FPS выключите DXVK в менеджере.", @"On NVIDIA GPUs, DXVK is usually slower than native DirectX 11 in CPU-bound games: translation adds CPU work. For max FPS, disable DXVK in the manager.",
            @"Наведите курсор на параметр, справа появится пример того, как он должен выглядеть.", @"Hover over a setting to see an example of how it should look on the right.",
            @"Свет движка", @"Engine lighting",
            @"Тени от всех источников света", @"Shadows from all lights",
            @"Ламп с тенями рядом с камерой", @"Shadowed lamps near camera",
            @"Окружающий свет", @"Ambient light",
            @"Окружающий свет на персонажах", @"Ambient light on characters",
            @"как в игре{0}", @"game default{0}",
            @"Добавка рассеянного света", @"Extra ambient light",
            @"нет", @"none",
            @"Отражения окружения", @"Environment reflections",
            @"Сила SSAO", @"SSAO strength",
            @"Радиус SSAO", @"SSAO radius",
            @"SSAO высокого качества", @"High-quality SSAO",
            @"NepFX, трассировка лучей по экрану", @"NepFX, screen-space ray tracing",
            @"Включить NepFX", @"Enable NepFX",
            @"Состояние: ", @"Status: ",
            @". Работа: ", @". Running: ",
            @"Сравнение половинами экрана", @"Split-screen comparison",
            @"Применять в меню и на портретах отряда", @"Apply in menus and party portraits",
            @"Эффект на персонажах", @"Effect on characters",
            @"Сила отражённого света", @"Indirect light strength",
            @"Радиус GI", @"GI radius",
            @"Затенение AO", @"AO shading",
            @"Дальность эффекта", @"Effect distance",
            @"Длина контактных теней", @"Contact shadow length",
            @"Сила контактных теней", @"Contact shadow strength",
            @"Отражения по экрану", @"Screen-space reflections",
            @"Включить отражения", @"Enable reflections",
            @"Сила отражений", @"Reflection strength",
            @"Дальность отражений", @"Reflection distance",
            @"Что отражает", @"Reflective surfaces",
            @"вода и мокрое", @"water and wet",
            @"плюс весь пол", @"plus all floors",
            @"все поверхности", @"all surfaces",
            @"Размытые отражения", @"Blurred reflections",
            @"Тени от света сверху", @"Overhead light shadows",
            @"Тени сверху и на открытом воздухе без солнца", @"Overhead shadows outdoors without sun",
            @"Тень под персонажами в помещениях", @"Floor shadow under characters indoors",
            @"Длина теней сверху", @"Overhead shadow length",
            @"Контактные тени от солнца в пещерах", @"Sun contact shadows in caves",
            @"Качество эффекта", @"Effect quality",
            @"Накопление кадров", @"Temporal accumulation",
            @"Лучей на пиксель", @"Rays per pixel",
            @"1, быстро", @"1, fast",
            @"4, качество", @"4, quality",
            @"Отладочный вид", @"Debug view",
            @"только отражённый свет", @"indirect light only",
            @"только затенение", @"shading only",
            @"контактные тени", @"contact shadows",
            @"нормали", @"normals",
            @"проверка вывода", @"output test",
            @"глубина", @"depth",
            @"маска персонажей", @"character mask",
            @"только отражения", @"reflections only",
            @"Для диагностики", @"Diagnostics",
            @"Источник глубины", @"Depth source",
            @"текстура игры", @"game texture",
            @"своя копия, MSAA", @"own copy, MSAA",
            @"своя копия, без MSAA", @"own copy, no MSAA",
            @"Момент в кадре", @"Frame injection point",
            @"перед постобработкой", @"before post-processing",
            @"после прозрачных", @"after transparents",
            @"до прозрачных", @"before transparents",
            @"после постобработки", @"after post-processing",
            @"Тест встраивания в рендер", @"Render injection test",
            @"Если в режиме «глубина» экран целиком синий, эффекту не на чем считать. Переключайте «Источник глубины» и «Момент в кадре», пока не появится картинка: близкое светлое, далёкое тёмное.", @"If the screen is fully blue in ""depth"" view, the effect has no data to work with. Switch ""Depth source"" and ""Frame injection point"" until an image appears: near is bright, far is dark.",
            @"Жесты в простое", @"Idle gestures",
            @"Жесты, когда героиня стоит", @"Gestures when a heroine stands still",
            @"Первый жест через, минимум", @"First gesture after, minimum",
            @"Первый жест через, максимум", @"First gesture after, maximum",
            @"Плавность переходов", @"Transition smoothness",
            @"Сторонние анимации", @"Custom animations",
            @"Использовать сторонние анимации", @"Use custom animations",
            @"Доля среди жестов", @"Share among gestures",
            @"Длительность", @"Duration",
            @"Сторонние: ", @"Custom: ",
            @"Поверх любой анимации", @"On top of any animation",
            @"Дыхание", @"Breathing",
            @"Сила дыхания", @"Breathing strength",
            @"Взгляд на камеру", @"Look at camera",
            @"Смотрит в камеру ближе чем", @"Looks at camera closer than",
            @"Героинь под управлением: {0}, сейчас играют жест: {1}. {2}", @"Heroines controlled: {0}, playing a gesture now: {1}. {2}",
            @"Жесты берутся из анимаций самой игры: ожидание, руки на поясе, кивок, покачивание головой, радость. Если героиня сдвинется с места, жест прервётся.", @"Gestures come from the game's own animations: waiting, hands on hips, nod, head shake, joy. If the heroine moves, the gesture stops.",
            @"Режим оверлея", @"Overlay mode",
            @"Положение", @"Position",
            @"слева сверху", @"top left",
            @"справа сверху", @"top right",
            @"слева снизу", @"bottom left",
            @"справа снизу", @"bottom right",
            @"Прозрачность фона", @"Background opacity",
            @"Клавиша переключения режимов: {0}. Оверлей рисуется самой игрой и не конфликтует с DXVK, в отличие от RivaTuner.", @"Mode toggle key: {0}. The overlay is drawn by the game itself and, unlike RivaTuner, doesn't conflict with DXVK.",
            @" Вкл", @" On",
            @" Выкл", @" Off",
            @"рекомендуется: ", @"recommended: ",
            @"без MSAA", @"no MSAA",
            @" + SMAA низк.", @" + SMAA low",
            @" + SMAA сред.", @" + SMAA medium",
            @" + SMAA выс.", @" + SMAA high",
            @"{0} | {1} FPS {2} мс | GPU {3} {4} | VRAM {5} ГБ | CPU {6}", @"{0} | {1} FPS {2} ms | GPU {3} {4} | VRAM {5} GB | CPU {6}",
            @"NepFix {0} · API: {1} · {2}×{3} @ {4} Гц", @"NepFix {0} · API: {1} · {2}×{3} @ {4} Hz",
            @"FPS {0}, цель {1}{2} · кадр {3} мс · 1% low {4} · мин/макс {5}/{6} мс · ограничивает: {7}", @"FPS {0}, target {1}{2} · frame {3} ms · 1% low {4} · min/max {5}/{6} ms · limited by: {7}",
            @"GPU {0} · {1} · {2} · {3} · {4}/{5} · вент. {6}", @"GPU {0} · {1} · {2} · {3} · {4}/{5} · fan {6}",
            @"VRAM {0} / {1} ГБ, игра {2} ГБ · шина памяти {3} · {4}", @"VRAM {0} / {1} GB, game {2} GB · memory bus {3} · {4}",
            @"CPU {0} · {1}, игра {2} · потоков игры {3} · ядер {4}", @"CPU {0} · {1}, game {2} · game threads {3} · cores {4}",
            @"RAM {0} / {1} ГБ, игра {2} ГБ, личная память {3} ГБ", @"RAM {0} / {1} GB, game {2} GB, private memory {3} GB",
            @"Рендер: профиль {0} · масштаб {1}{2} · {3} · тени {4} · LOD {5}", @"Render: profile {0} · scale {1}{2} · {3} · shadows {4} · LOD {5}",
            @"Игра: множитель времени {0} · тайминг {1} · драйвер {2} · {3}", @"Game: time scale {0} · timing {1} · driver {2} · {3}",
            @"время кадра, шкала {0} мс", @"frame time, scale {0} ms",
            @"вкл", @"on",
            @"Лампы и фонари начинают отбрасывать тени. Солнце не трогается: у второго солнца игра тени отключила специально. Сфера и куб закрывают свет лампы, за ними появляется тёмная область.", @"Lamps and torches start casting shadows. The sun is left alone: the game turned off shadows for the second sun on purpose. The sphere and the cube block the lamp, and a dark area appears behind them.",
            @"Ламп с тенями", @"Shadowed lamps",
            @"Сколько ближайших к камере ламп получают тени. Каждая лампа с тенями заново рисует сцену до шести раз, на слабом процессоре ставьте 2.", @"How many lamps nearest to the camera get shadows. Each shadowed lamp redraws the scene up to six times, so use 2 on a weak CPU.",
            @"меньше", @"less",
            @"больше", @"more",
            @"Яркость рассеянного света неба. Больше значение, светлее стороны объектов, куда не попадает солнце, и мягче тени.", @"Brightness of ambient sky light. Higher values brighten the sides of objects the sun doesn't reach and soften shadows.",
            @"Шейдер персонажей сам решает, сколько рассеянного света принять. При нуле теневая сторона персонажа не зависит от окружения, при единице подкрашивается цветом неба и сцены.", @"The character shader decides how much ambient light to take. At zero the shadowed side ignores the surroundings, at one it is tinted by the sky and scene colors.",
            @"Нужна там, где игра обнулила окружающий свет и множитель ничего не меняет. Тени перестают быть чёрными провалами.", @"Needed where the game set ambient light to zero and the multiplier does nothing. Shadows stop being pitch-black holes.",
            @"Сила отражений на глянцевых поверхностях. Работает только если в сцене есть пробы отражений или отражение неба.", @"Reflection strength on glossy surfaces. Works only if the scene has reflection probes or a sky reflection.",
            @"Затемнение в углах, щелях и под предметами. Действует на окружение, шейдер персонажей его не поддерживает.", @"Darkening in corners, crevices and under objects. Affects the environment; the character shader doesn't support it.",
            @"высокая", @"high",
            @"Насколько сильно темнеют углы, стыки стен с полом и места под предметами.", @"How dark corners, wall-floor joints and areas under objects become.",
            @"маленький", @"small",
            @"большой", @"large",
            @"Маленький радиус даёт тонкую тёмную кромку только в стыках. Большой даёт широкое мягкое затемнение вокруг предметов.", @"A small radius gives a thin dark edge only at joints. A large one gives wide soft darkening around objects.",
            @"Полное разрешение и больше выборок: затенение без зерна и ступенек по краям, но немного дороже.", @"Full resolution and more samples: shading without grain or stair-stepping at the edges, but slightly more expensive.",
            @"Экранная трассировка лучей: отсвет от цветных стен на соседние предметы, затенение в углах и точные тени у основания предметов.", @"Screen-space ray tracing: colored bounce light from walls onto nearby objects, shading in corners and precise shadows at the base of objects.",
            @"сравнение", @"comparison",
            @"эффект целиком", @"full effect",
            @"Левая половина экрана рисуется без NepFX, правая с ним. По белой линии видно разницу прямо в игре.", @"The left half of the screen is drawn without NepFX, the right half with it. The white line shows the difference right in the game.",
            @"Цветной отсвет: красная стена подкрашивает сферу и пол рядом, освещённый пол подсвечивает низ предметов.", @"Colored bounce light: the red wall tints the sphere and the floor next to it, and the lit floor brightens the bottom of objects.",
            @"0.4 м", @"0.4 m",
            @"3 м", @"3 m",
            @"Как далеко ищется отражённый свет. Маленький радиус даёт отсвет только вплотную к поверхности, большой красит всю комнату.", @"How far bounce light is searched for. A small radius gives bounce only right next to surfaces, a large one tints the whole room.",
            @"Затемнение, рассчитанное трассировкой. Глубже и точнее, чем SSAO игры, работает и на персонажах.", @"Ray-traced shading. Deeper and more accurate than the game's SSAO, and it works on characters too.",
            @"0.5 м", @"0.5 m",
            @"Тень у самого основания предметов, которую карта теней теряет. Жёлтый кубик перестаёт висеть над полом.", @"The shadow right at the base of objects that the shadow map misses. The yellow cube stops floating above the floor.",
            @"Вода и мокрые поверхности отражают то, что видно на экране: героинь, стены, предметы. Под острым углом отражение сильнее, как в жизни. Чего нет в кадре, отразиться не может, поэтому у края экрана отражение плавно исчезает.", @"Water and wet surfaces reflect what is on screen: heroines, walls, objects. At grazing angles the reflection is stronger, as in real life. What is off-screen can't be reflected, so reflections fade out near the screen edge.",
            @"слабо", @"weak",
            @"сильно", @"strong",
            @"Насколько заметны отражения. При 100% пол похож на зеркало, для каменных полов и земли лучше 30–50%.", @"How visible reflections are. At 100% the floor looks like a mirror; 30–50% is better for stone floors and ground.",
            @"близко", @"near",
            @"далеко", @"far",
            @"Как далеко ищется отражаемый объект. Больше значение, дальше видны отражения, но ниже FPS.", @"How far the reflected object is searched for. Higher values show reflections farther away but lower FPS.",
            @"без отражений", @"no reflections",
            @"с отражениями", @"with reflections",
            @"По умолчанию отражают только вода и мокрые поверхности: их мод находит по шейдерам игры. «Плюс весь пол» добавляет любой горизонтальный пол, включая песок и землю. «Все поверхности» включает и стены.", @"By default only water and wet surfaces reflect: the mod finds them by the game's shaders. ""Plus all floors"" adds any horizontal floor, including sand and ground. ""All surfaces"" includes walls too.",
            @"чёткие", @"sharp",
            @"размытые", @"blurred",
            @"Размытие делает отражение похожим на полированный камень, а не на зеркало, и скрывает зубчатые края.", @"Blur makes reflections look like polished stone rather than a mirror and hides jagged edges.",
            @"В шахтах и пещерах освещение запечено заранее, а солнце игры светит только на персонажей, поэтому на полу нет их теней. NepFX добавляет тень от условного света сверху: под ногами и предметами появляется мягкое тёмное пятно.", @"In mines and caves the lighting is baked in advance, and the game's sun lights only the characters, so they cast no shadows on the floor. NepFX adds a shadow from a virtual overhead light: a soft dark spot appears under feet and objects.",
            @"полностью", @"full",
            @"Насколько тёмной будет контактная тень.", @"How dark the contact shadow is.",
            @"Результат нескольких кадров усредняется, зерно пропадает. Слишком большое значение даёт шлейфы за движущимися персонажами.", @"Several frames are averaged so the grain disappears. Too high a value leaves trails behind moving characters.",
            @"Больше лучей, меньше шума, но ниже FPS.", @"More rays, less noise, but lower FPS.",
            @"Отладка: только отражённый свет", @"Debug: indirect light only",
            @"обычный вид", @"normal view",
            @"отладка", @"debug",
            @"Показывает только найденный отсвет. Чёрное это места без отсвета. Небо закрашено синим.", @"Shows only the bounce light found. Black means no bounce. The sky is painted blue.",
            @"Отладка: только затенение", @"Debug: shading only",
            @"Белое не затенено, тёмное затенено. Углы и места под предметами должны быть темнее.", @"White is unshaded, dark is shaded. Corners and areas under objects should be darker.",
            @"Отладка: контактные тени", @"Debug: contact shadows",
            @"Тёмными пятнами видны только контактные тени у основания предметов.", @"Only the contact shadows at the base of objects show as dark spots.",
            @"Отладка: нормали", @"Debug: normals",
            @"Пол зелёный, стены красноватые и синеватые, сфера переливается. Если так, буфер глубины читается правильно.", @"The floor is green, walls reddish and bluish, the sphere iridescent. If so, the depth buffer is read correctly.",
            @"Отладка: проверка вывода", @"Debug: output test",
            @"Вся 3D-сцена окрашивается в красный. Не окрасилась, значит проход не попадает в кадр.", @"The whole 3D scene turns red. If it doesn't, the pass isn't reaching the frame.",
            @"Отладка: глубина", @"Debug: depth",
            @"Близкое светлое, далёкое тёмное, небо синее. Если весь экран синий, игра не отдаёт буфер глубины.", @"Near is bright, far is dark, sky is blue. If the whole screen is blue, the game doesn't provide a depth buffer.",
            @"как монитор", @"monitor",
            @"выкл, если FPS хватает", @"off, if FPS is enough",
            @"60 м", @"60 m",
            @"140 мс", @"140 ms",
            @"180 мс", @"180 ms",
            @"120 мс", @"120 ms",
            @"40 с", @"40 s",
            @"40 мс", @"40 ms",
            @"2,00 м", @"2.00 m",
            @"0,35 м", @"0.35 m",
            @"15 м", @"15 m",
            @"0,8 м", @"0.8 m",
            @"40 м", @"40 m",
            @"Мотоцикл сейчас не используется.", @"The bike is not in use right now.",
            @"Шаг физики {0} в секунду. Сейчас поворот {1}°/с, в игре {2}. Скорость до {3}, в игре {4}. Торможение о стену {5}, в игре {6}.", @"Physics step {0} per second. Turn rate now {1}°/s, game default {2}. Top speed {3}, game default {4}. Wall braking {5}, game default {6}.",
            @"Мотоцикл: ", @"Bike: ",
            @"Замер идёт: строк {0}, столкновений {1}, скорость {2}.", @"Recording: rows {0}, crashes {1}, speed {2}.",
            @"Замер: ", @"Recording: ",
            @"Замер включён: сядьте на мотоцикл.", @"Recording is on: get on the bike.",
            @"болтовня в пути", @"chatter on the road",
            @"нашла механизм", @"found a mechanism",
            @"прыжок", @"jump",
            @"удар по врагу на карте", @"field attack on an enemy",
            @"стоим без дела", @"standing idle",
            @"категория ", @"category ",
            @", пропущена", @", skipped",
            @"Фраз звучало {0}, пропущено {1}. Последняя: {2}.", @"Lines played {0}, skipped {1}. Last: {2}.",
            @"пакет шейдеров не загружен", @"shader bundle not loaded",
            @"материал не создан", @"material not created",
            @"проход ни разу не выполнился", @"the pass has never run",
            @"выполняется {0} раз/с, камера {1}, глубина: {2}", @"running {0} times/s, camera {1}, depth: {2}",
            @", над отрядом потолок, тени сверху включены, теней под персонажами {0}{1}, моделей персонажей {2}", @", ceiling above the party, overhead shadows on, floor shadows under characters {0}{1}, character models {2}",
            @", туман сцены: {0}", @", scene fog: {0}",
            @", пропуск: {0}", @", skipped: {0}",
            @". Ошибка: ", @". Error: ",
            @". Ошибок MSAA в секунду: {0}", @". MSAA errors per second: {0}",
            @"нет файла nepfx.bundle, соберите проект NepFX_Unity", @"nepfx.bundle is missing, build the NepFX_Unity project",
            @"не удалось открыть nepfx.bundle", @"could not open nepfx.bundle",
            @"в пакете нет шейдера", @"no shader in the bundle",
            @"шейдер не поддерживается этой видеокартой", @"the shader is not supported by this GPU",
            @"загружен, {0}, проходов {1}", @"loaded, {0}, passes {1}",
            @"ошибка загрузки: ", @"load error: ",
            @"нет камеры", @"no camera",
            @"камера-наложение ", @"overlay camera ",
            @"ортографическая камера ", @"orthographic camera ",
            @"камера редактора/превью", @"editor/preview camera",
            @"камера меню ", @"menu camera ",
            @"линейный {0}–{1} м", @"linear {0}–{1} m",
            @"плотность {0}", @"density {0}",
            @"старый nepfx.bundle, запустите build_nepfx.bat", @"old nepfx.bundle, run build_nepfx.bat",
            @"своя копия, MSAA {0}x", @"own copy, MSAA {0}x",
            @"текстура игры _CameraDepthTexture", @"game texture _CameraDepthTexture",
            @"нужен новый nepfx.bundle, запустите build_nepfx.bat", @"a newer nepfx.bundle is needed, run build_nepfx.bat",
            @"Источников света: направленных {0}, с тенями {1}; точечных и прожекторов {2}, с тенями {3}. ", @"Lights: directional {0}, with shadows {1}; point and spot {2}, with shadows {3}. ",
            @"Освещение сцены: ", @"Scene lighting: ",
            @"пещера {0} (потолок {1}, карт освещения {2}, рассеянный свет {3}, солнц с тенями {4})", @"cave {0} (ceiling {1}, lightmaps {2}, ambient light {3}, shadowed suns {4})",
            @"от неба", @"skybox",
            @"три цвета", @"trilight",
            @"один цвет", @"flat color",
            @"свой", @"custom",
            @"Сцена: окружающий свет {0}, яркость по игре {1}, карт освещения {2}, световых проб {3}, проб отражений {4}.", @"Scene: ambient light {0}, game brightness {1}, lightmaps {2}, light probes {3}, reflection probes {4}.",
            @" Рассеянного света в сцене нет, поэтому множитель ничего не меняет. Используйте «Добавка рассеянного света».", @" The scene has no ambient light, so the multiplier changes nothing. Use ""Extra ambient light"".",
            @" Статичные объекты освещены запечёнными картами, окружающий свет влияет в основном на персонажей и подвижные объекты.", @" Static objects are lit by baked lightmaps; ambient light mostly affects characters and moving objects.",
            @" Проб отражений нет, ползунок отражений влияет только на отражение неба.", @" There are no reflection probes; the reflections slider only affects the sky reflection.",
            @"Сцена: ", @"Scene: ",
            @"SSAO: сила {0}→{1}, радиус {2}→{3}, выборок {4}, пониж. разрешение {5}", @"SSAO: strength {0}→{1}, radius {2}→{3}, samples {4}, downsampled {5}",
            @" камеры: ", @" camera: ",
            @" тени: ", @" shadows: ",
            @" изменено групп LOD: {0}", @" LOD groups changed: {0}",
            @"Отсечение по слоям у камеры: {0} слоёв", @"Per-layer camera culling: {0} layers",
            @", {0}–{1} м по игре", @", {0}–{1} m by game",
            @". Тени по слоям: {0}. Групп LOD: {1}", @". Per-layer shadows: {0}. LOD groups: {1}",
            @", по игре объект исчезает, когда занимает меньше {0}–{1}% высоты экрана", @", by default an object disappears below {0}–{1}% of screen height",
            @". Объединённых LOD: {0}.", @". Merged LODs: {0}.",
            @"Плагин BepInEx", @"BepInEx plugin",
            @"загружен", @"loaded",
            @"не загружен", @"not loaded",
            @"Загрузчик", @"Loader",
            @"ошибка", @"error",
            @"Ошибка", @"Error",
            @"работает", @"running",
            @" параметров в dxvk.conf", @" settings in dxvk.conf",
            @"без dxvk.conf", @"no dxvk.conf",
            @"активен", @"active",
            @"d3d11.dll/dxgi.dll загружены из папки игры, ", @"d3d11.dll/dxgi.dll loaded from the game folder, ",
            @"не используется", @"not used",
            @"рендер через родной DirectX 11", @"rendering through native DirectX 11",
            @"Постобработка", @"Post-processing",
            @"меню Home, эффекты End · ", @"menu Home, effects End · ",
            @"эффекты: ", @"effects: ",
            @"Нативная DLL", @"Native DLL",
            @"загружена", @"loaded",
            @"Пакет файлов", @"File pack",
            @"выключен", @"disabled",
            @"включается в NepModManager.exe", @"enabled in NepModManager.exe",
            @"установлен", @"installed",
            @"частично", @"partial",
            @"файлов на месте: {0}/{1}", @"files in place: {0}/{1}",
            @", переустановите мод в менеджере: файлы могло перезаписать обновление игры", @", reinstall the mod in the manager: a game update may have overwritten the files",
            @"Текстуры персонажей сейчас не загружены — откройте меню отряда или выйдите на карту и проверьте снова.", @"Character textures are not loaded right now. Open the party menu or go to the field map and check again.",
            @"Текстур персонажей в памяти: {0}, из них HD 2048: {1}, обычных: {2}. ", @"Character textures in memory: {0}, HD 2048: {1}, regular: {2}. ",
            @"HD-текстуры работают.", @"HD textures are working.",
            @"HD-текстуры НЕ используются.", @"HD textures are NOT in use.",
            @"  Пример: ", @"  Example: ",
            @"Ошибка проверки: ", @"Check error: ",
            @"упор в лимит FPS", @"FPS limit reached",
            @"нет данных GPU", @"no GPU data",
            @"видеокарта", @"GPU",
            @"процессор, главный поток игры", @"CPU, game main thread",
            @"DirectX 11 → Vulkan через DXVK", @"DirectX 11 → Vulkan via DXVK",
            @"родной DirectX 11", @"native DirectX 11",
            @"неизвестно", @"unknown",
            @"выкл, масштаб вручную", @"off, manual scale",
            @"подбираю", @"tuning",
            @"ошибок нет", @"no errors",
            @"ошибки идут при выключенном NepFX, их вызывает сама игра", @"errors occur with NepFX off, the game itself causes them",
            @"перебрал оба способа, ошибки не от чтения глубины NepFX", @"tried both methods, the errors are not from NepFX depth reading",
            @"подбираю чтение глубины для камеры {0}", @"tuning depth reading for camera {0}",
            @"Блестящих объектов в сцене: вода {0}, мокрые {1}, гладкие {2}.", @"Glossy objects in scene: water {0}, wet {1}, smooth {2}.",
            @"Блеск: ", @"Gloss: ",
            @"физика волос ещё не запущена", @"hair physics not started yet",
            @"Физика волос и одежды: по игре {0} Гц, {1}; сейчас {2} Гц, {3}", @"Hair and cloth physics: game {0} Hz, {1}; now {2} Hz, {3}",
            @"Физика волос: ", @"Hair physics: ",
            @"карта", @"field",
            @"{0} МГц", @"{0} MHz",
            @"{0} Вт", @"{0} W",
            @"по реальному кадру", @"real frame time",
            @"игры", @"game",
            @"SSAO: сила {0}→{1}, радиус {2}→{3}, выборок {4}, пониж. разрешение нет", @"SSAO: strength {0}→{1}, radius {2}→{3}, samples {4}, downsampled no",
            @"SSAO: сила {0}→{1}, радиус {2}→{3}, выборок {4}, пониж. разрешение да", @"SSAO: strength {0}→{1}, radius {2}→{3}, samples {4}, downsampled yes",
            @"Непрозрачность меню", @"Menu opacity",
            @"Непрозрачность фона меню (0–1). 1 = сплошной тёмный фон, удобно для скриншотов.", @"Menu background opacity (0–1). 1 = solid dark background, handy for screenshots.",
            @"Лимит FPS. 0 = частота обновления монитора. Не ставьте выше, чем может выдать ПК: игра считает время от целевого FPS.", @"FPS limit. 0 = monitor refresh rate. Don't set it higher than your PC can deliver: the game measures time from the target FPS.",
            @"Вертикальная синхронизация.", @"Vertical sync.",
            @"Управлять частотой кадров (иначе игра держит 60).", @"Control the framerate (otherwise the game holds 60).",
            @"Базовый профиль Unity: -1 как в игре, 0 Normal, 1 Low, 2 Medium, 3 High, 4 Ultra.", @"Base Unity profile: -1 game default, 0 Normal, 1 Low, 2 Medium, 3 High, 4 Ultra.",
            @"Текстуры в полном разрешении (профиль игры Normal грузит их в 1/2).", @"Full-resolution textures (the game's Normal profile loads them at 1/2).",
            @"Анизотропная фильтрация (0 = как в игре, 2-16).", @"Anisotropic filtering (0 = game default, 2-16).",
            @"Скиннинг 4+ кости на вершину (игра: 2) — плавнее сгибы суставов.", @"Skinning with 4+ bones per vertex (game: 2), smoother joint bending.",
            @"MSAA: 1 (выкл), 2, 4, 8.", @"MSAA: 1 (off), 2, 4, 8.",
            @"Пост-сглаживание камеры.", @"Camera post-process anti-aliasing.",
            @"Масштаб рендера 0.5–2.0. >1 = суперсэмплинг (лучшее против лесенок), <1 = апскейл.", @"Render scale 0.5–2.0. >1 = supersampling (best against jaggies), <1 = upscaling.",
            @"Режим FSR: 0 выкл, 1 Native AA, 2 Quality 1.5x, 3 Balanced 1.7x, 4 Performance 2x, 5 Ultra Performance 3x.", @"FSR mode: 0 off, 1 Native AA, 2 Quality 1.5x, 3 Balanced 1.7x, 4 Performance 2x, 5 Ultra Performance 3x.",
            @"Множитель дальности появления растительности и мелких объектов, 8 = без отсечения.", @"Draw distance multiplier for grass and small objects, 8 = no culling.",
            @"Фильтр при RenderScale < 1: FSR1 — AMD FidelityFX Super Resolution 1.0.", @"Filter when RenderScale < 1: FSR1 = AMD FidelityFX Super Resolution 1.0.",
            @"Резкость FSR (0–1).", @"FSR sharpness (0–1).",
            @"HDR-рендеринг (внутренний буфер).", @"HDR rendering (internal buffer).",
            @"Управлять тенями из мода.", @"Control shadows from the mod.",
            @"Разрешение карты теней: 1024/2048/4096/8192.", @"Shadow map resolution: 1024/2048/4096/8192.",
            @"Минимальная дальность теней (карты игры местами ставят почти 0 — тени пропадают).", @"Minimum shadow distance (some game maps set it close to 0 and shadows disappear).",
            @"Множитель дальности теней, заданной картой.", @"Multiplier for the map's shadow distance.",
            @"Каскады теней 1–4.", @"Shadow cascades 1–4.",
            @"Мягкие тени.", @"Soft shadows.",
            @"Тени от точечных/прожекторных источников.", @"Shadows from point and spot lights.",
            @"Ambient occlusion (если есть в рендерере игры).", @"Ambient occlusion (if present in the game renderer).",
            @"LOD Bias: выше = детальные модели дальше (1 = как в игре).", @"LOD Bias: higher = detailed models farther away (1 = game default).",
            @"Множитель дальности отсечения камеры.", @"Camera far clip distance multiplier.",
            @"Отключить упрощение объектов карты вблизи (MapReduction).", @"Disable simplification of nearby map objects (MapReduction).",
            @"Враги не застревают на месте при высоком FPS: порог «юнит упёрся» пересчитывается под время кадра.", @"Enemies don't get stuck at high FPS: the ""unit is blocked"" threshold is recalculated for frame time.",
            @"Скорость игровых процессов по реальному времени кадра (против тряски камеры/персонажей при просадках FPS).", @"Game process speed based on real frame time (against camera/character shake during FPS drops).",
            @"Интерполяция физических тел (против дёрганья при беге).", @"Rigidbody interpolation (against stutter while running).",
            @"Шаг физики = 1/FPS (эксперимент).", @"Physics step = 1/FPS (experimental).",
            @"Постановка ступней по земле. Выключение убирает дрожание ног при медленной ходьбе, но на склонах ступни могут чуть уходить в землю или висеть.", @"Foot placement on the ground. Turning it off removes leg jitter when walking slowly, but on slopes feet may sink into the ground or float a little.",
            @"Физика волос и одежды: 0 как в игре, 1 частота под FPS, 2 раз в кадр.", @"Hair and cloth physics: 0 game default, 1 rate matched to FPS, 2 once per frame.",
            @"Жесты из анимаций игры, когда героиня стоит без дела.", @"Gestures from the game's animations when a heroine stands idle.",
            @"Через сколько секунд простоя может начаться жест, минимум.", @"Seconds of idling before a gesture may start, minimum.",
            @"То же, максимум.", @"Same, maximum.",
            @"Длительность плавного перехода между анимациями, секунды.", @"Duration of the smooth transition between animations, seconds.",
            @"Сторонние idle-анимации из nepidle.bundle.", @"Custom idle animations from nepidle.bundle.",
            @"Доля сторонних анимаций среди жестов.", @"Share of custom animations among gestures.",
            @"Сколько секунд длится сторонняя анимация, округляется до целых повторов.", @"How many seconds a custom animation lasts, rounded to whole loops.",
            @"Дыхание: грудная клетка и плечи чуть поднимаются.", @"Breathing: chest and shoulders rise slightly.",
            @"Сила дыхания.", @"Breathing strength.",
            @"Героиня поворачивает голову к камере, когда стоит рядом.", @"The heroine turns her head to the camera when standing close.",
            @"На каком расстоянии от камеры героиня смотрит в неё, метры.", @"Distance from the camera at which the heroine looks at it, meters.",
            @"Оружие при ударе вне боя появляется и исчезает плавно, а не мгновенно.", @"On field attacks the weapon appears and disappears smoothly instead of instantly.",
            @"Длительность появления и исчезновения оружия, секунды.", @"Weapon appear/disappear duration, seconds.",
            @"Плавное движение отряда и мотоцикла между шагами физики игры.", @"Smooth party and bike movement between the game's physics steps.",
            @"Управляемость мотоцикла: множитель скорости поворота. 1 как в игре.", @"Bike handling: turn rate multiplier. 1 = game default.",
            @"Максимальная скорость мотоцикла: множитель. 1 как в игре.", @"Bike top speed multiplier. 1 = game default.",
            @"Мягкость ударов о стену: 0 как в игре, 1 мотоцикл почти не теряет скорость.", @"Wall hit softness: 0 game default, 1 the bike barely loses speed.",
            @"Сглаживание подъёма мотоцикла на уступы, секунды. 0 как в игре.", @"Bike ledge climb smoothing, seconds. 0 = game default.",
            @"Замер езды на мотоцикле в BepInEx\NepFix_bike.csv. Выключается сам после записи.", @"Bike ride recording to BepInEx\NepFix_bike.csv. Turns itself off after recording.",
            @"Ограничить яркость цветных ламп на персонажах (_Is_Filter_LightColor шейдера Toon). В пещерах лампы игры светят с силой 10 и засвечивают героинь.", @"Limit colored lamp brightness on characters (_Is_Filter_LightColor of the Toon shader). In caves the game's lamps have intensity 10 and blow out the heroines.",
            @"Минимальная пауза между фразами героинь на карте вне боя, секунды. 0 как в игре.", @"Minimum pause between heroine voice lines on the field outside battle, seconds. 0 = game default.",
            @"Минимальная длительность перехода между анимациями на карте, секунды. У игры 0.1.", @"Minimum animation transition duration on the field, seconds. The game uses 0.1.",
            @"Сглаживание высоты моделей персонажей между шагами физики: убирает дрожь ног и волос при ходьбе на высоком FPS.", @"Character model height smoothing between physics steps: removes leg and hair jitter when walking at high FPS.",
            @"Время сглаживания высоты, секунды.", @"Height smoothing time, seconds.",
            @"Аниматоры не отключаются вне кадра (эксперимент).", @"Animators are not disabled off-screen (experimental).",
            @"Кадров в очереди GPU (0 = как в игре, 1 = меньше задержка, 2–3 = ровнее).", @"GPU queued frames (0 = game default, 1 = lower latency, 2–3 = smoother).",
            @"Не пересчитывать скиннинг моделей вне кадра.", @"Don't compute skinning for off-screen models.",
            @"Аниматоры вне кадра не обновляют кости (эксперимент, экономит CPU при толпе NPC).", @"Off-screen animators don't update bones (experimental, saves CPU in NPC crowds).",
            @"Физика без авто-синхронизации трансформов: меньше нагрузка на CPU, но у персонажей может дрожать постановка ног.", @"Physics without transform auto-sync: lower CPU load, but character foot placement may jitter.",
            @"Ускоренная загрузка ресурсов: больше времени и буфера на загрузку текстур/мешей в GPU, высокий приоритет фоновой загрузки.", @"Faster asset loading: more time and buffer for uploading textures/meshes to the GPU, high background loading priority.",
            @"Mip bias текстур: отрицательное = резче вдали (земля, стены), 0 = как в игре.", @"Texture mip bias: negative = sharper at a distance (ground, walls), 0 = game default.",
            @"Экранное освещение NepFX (нужен nepfx.bundle).", @"NepFX screen-space lighting (requires nepfx.bundle).",
            @"Сила отражённого света.", @"Indirect light strength.",
            @"Радиус трассировки GI, метры.", @"GI tracing radius, meters.",
            @"Сила затенения (AO) от трассировки.", @"Ray-traced shading (AO) strength.",
            @"Длина контактных теней, метры.", @"Contact shadow length, meters.",
            @"Сила контактных теней.", @"Contact shadow strength.",
            @"Вес истории кадров (меньше = меньше шлейфов, больше шума).", @"Frame history weight (lower = fewer trails, more noise).",
            @"Лучей на пиксель (половинное разрешение).", @"Rays per pixel (half resolution).",
            @"Шагов на луч.", @"Steps per ray.",
            @"Использовать векторы движения игры.", @"Use the game's motion vectors.",
            @"Отладка: 0 выкл, 1 GI, 2 AO, 3 контактные тени, 4 нормали, 5 проверка вывода, 6 глубина.", @"Debug: 0 off, 1 GI, 2 AO, 3 contact shadows, 4 normals, 5 output test, 6 depth.",
            @"Откуда брать глубину: 0 авто, 1 текстура игры, 2 своя копия с MSAA, 3 своя копия без MSAA.", @"Depth source: 0 auto, 1 game texture, 2 own copy with MSAA, 3 own copy without MSAA.",
            @"Момент в кадре: 0 перед постобработкой, 1 после прозрачных, 2 после неба, 3 после постобработки.", @"Frame injection point: 0 before post-processing, 1 after transparents, 2 after skybox, 3 after post-processing.",
            @"Применять NepFX к камерам, которые рисуют в текстуру: портреты отряда и сцены в меню.", @"Apply NepFX to cameras that render to a texture: party portraits and menu scenes.",
            @"Сила NepFX на персонажах: затенение, отсвет и контактные тени. 0 персонажи без эффекта, 1 как на окружении.", @"NepFX strength on characters: shading, bounce light and contact shadows. 0 = no effect on characters, 1 = same as environment.",
            @"Если в сцене нет солнца, контактные тени строятся от условного света сверху: тени под персонажами и предметами в шахтах и пещерах.", @"If the scene has no sun, contact shadows are cast from a virtual overhead light: shadows under characters and objects in mines and caves.",
            @"Тени от света сверху и на открытом воздухе, если в сцене нет солнца с тенями. По умолчанию только под потолком: в шахтах, пещерах, зданиях.", @"Overhead light shadows outdoors too, if the scene has no shadowed sun. By default only under a ceiling: in mines, caves, buildings.",
            @"Отражения по экрану: вода, пол, глянцевые поверхности.", @"Screen-space reflections: water, floors, glossy surfaces.",
            @"Сила отражений.", @"Reflection strength.",
            @"Дальность отражений, метры.", @"Reflection distance, meters.",
            @"Что отражает: 0 вода и мокрые поверхности, 1 плюс весь пол, 2 все поверхности.", @"Reflective surfaces: 0 water and wet surfaces, 1 plus all floors, 2 all surfaces.",
            @"Размытые отражения, как у неровной поверхности.", @"Blurred reflections, like on a rough surface.",
            @"Сила мягкой тени на полу под персонажами в помещениях.", @"Strength of the soft floor shadow under characters indoors.",
            @"Дальше этого расстояния затенение и отсвет плавно сходят на нет. Вдали картинка в тумане, и эффект темнил туман вокруг деревьев.", @"Beyond this distance shading and bounce light fade out smoothly. Far away the image is in fog, and the effect used to darken the fog around trees.",
            @"Длина теней от условного света сверху, метры.", @"Length of shadows from the virtual overhead light, meters.",
            @"Сравнение: левая половина экрана без NepFX, правая с ним.", @"Comparison: left half of the screen without NepFX, right half with it.",
            @"Тест встраивания в рендер: пурпурный квадрат в левом нижнем углу 3D-сцены (под интерфейсом).", @"Render injection test: a magenta square in the lower left corner of the 3D scene (under the UI).",
            @"Служебное: камеры, для которых глубина читается другим способом, чтобы не было ошибок MSAA.", @"Internal: cameras whose depth is read another way to avoid MSAA errors.",
            @"Служебное: момент эффекта перенесён до прозрачных объектов.", @"Internal: the effect injection point was moved before transparent objects.",
            @"Контактные тени от солнца в пещерах и шахтах. Солнце там светит только на персонажей, поэтому по умолчанию выключено.", @"Sun contact shadows in caves and mines. The sun there lights only the characters, so it is off by default.",
            @"Тени от ламп и фонарей, у которых игра их отключила. Направленный свет не трогается.", @"Shadows from lamps and torches where the game turned them off. Directional light is left alone.",
            @"Сколько ближайших ламп/прожекторов отбрасывают тени (каждый — до 6 проходов рендера).", @"How many nearest lamps/spotlights cast shadows (each costs up to 6 render passes).",
            @"Множитель окружающего (рассеянного) света сцены.", @"Scene ambient light multiplier.",
            @"Сколько окружающего света принимают персонажи, параметр _GI_Intensity шейдера Toon. -1 как в игре.", @"How much ambient light characters receive, the _GI_Intensity parameter of the Toon shader. -1 = game default.",
            @"Добавка рассеянного света, если в сцене его нет совсем.", @"Extra ambient light for scenes that have none at all.",
            @"Множитель отражений окружения.", @"Environment reflection multiplier.",
            @"Сила SSAO относительно игры.", @"SSAO strength relative to the game.",
            @"Радиус SSAO относительно игры.", @"SSAO radius relative to the game.",
            @"SSAO в полном разрешении и минимум 8 выборок.", @"SSAO at full resolution with at least 8 samples.",
            @"Клавиша меню (F1–F12).", @"Menu key (F1–F12).",
            @"Положение окна меню (перетаскивается за заголовок).", @"Menu window position (drag it by the title).",
            @"Положение окна меню.", @"Menu window position.",
            @"Множитель толщины контура персонажей (0 = авто по разрешению: высота/1080).", @"Character outline width multiplier (0 = auto by resolution: height/1080).",
            @"Принудительно включить отбрасывание теней всеми частями моделей персонажей (выкл = как задумано игрой).", @"Force shadow casting on all parts of character models (off = as the game intends).",
            @"Оверлей мониторинга: 0 выкл, 1 компактный, 2 подробный, 3 подробный + график.", @"Performance overlay: 0 off, 1 compact, 2 detailed, 3 detailed + graph.",
            @"Угол оверлея: 0 слева сверху, 1 справа сверху, 2 слева снизу, 3 справа снизу.", @"Overlay corner: 0 top left, 1 top right, 2 bottom left, 3 bottom right.",
            @"Клавиша переключения режимов оверлея.", @"Overlay mode toggle key.",
            @"Непрозрачность фона оверлея (0–1).", @"Overlay background opacity (0–1).",
            @"Счётчик FPS в углу.", @"FPS counter in the corner.",
            @"Подробный лог диагностики.", @"Verbose diagnostic log.",
            @"Язык меню: auto по языку системы, ru русский, en английский.", @"Menu language: auto follows the system language, ru Russian, en English.",
            @"Язык", @"Language",
        };
    }
}
